# MSBA 605-77 - Python for Analytics
## Problem Solving Exercise 3
### Logisitics
1. Get into your weekly group.
1. Discuss and complete the assignment __together__. Don’t just assign different problems to each teammate! That defeats the purpose of team-based learning.
1. Choose a recorder to prepare the final copy to submit to instructor in Blackboard. __Only one person needs to submit__ on behalf of the team.

__Names of group members__: Jonathan Thompson, Uchechukwu Okonkwo, Simran Likhitapudi<br>
__Due__: Sunday, October 22 (by 11:59 PM)

Add your code to the cells below. When finished, be sure to save your notebook, then _Close and Shutdown Notebook_ from the _File_ menu. Return to Blackboard and have recorder upload your completed Notebook file (`PSE3.ipynb`) on behalf of the group.

In [1]:
import numpy as np

## Part 1 

### Problem 1
In the code cell below, write a Python script that uses NumPy to create an array of 10 zeros, an array of 10 ones, and an array of 10 fives. Use NumPy methods `zeros` and `ones`. You can multiply an array by a scalar like `5` to get the third result. Print each array. (3 pts.)

In [9]:
import numpy as np

array=np.zeros(10)
print("Array of 10 zeros:")
print(array)
array2=np.ones(10)
print("Array of 10 ones:")
print(array2)
array3=np.ones(10)*5
print("Array of 10 fives:")
print(array3)


Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Problem 2
In the code cell below, write a Python script that uses NumPy to create an array of integers from 25 to 50 (inclusive) using NumPy method `arange`. Print the array. Also, print the `dtype` attribute of this array to see which integer type was used to represent the data. (2 pts.)

In [68]:
import numpy as np

array=np.arange(25,51)
print("Array range:")
print (array)

print("")
print(f'dtype: == {array.dtype}')

Array range:
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

dtype: == int32


### Problem 3
In the code cell below, write a Python script that uses NumPy to create a 2-by-2 array containing the numbers 0–3 using `arange` and `reshape`. Use broadcasting to perform each of the following operations on the original array creating a new array and printing its contents (5 pts.):
1. Cube every element of the array.
1. Add 7 to every element of the array.
1. Multiply every element of the array by 2. 

In [64]:
import numpy as np

array = np.arange(0,4).reshape((2, 2))
print (array)

print("")
print (array **3)

print("")
print (np.add(array, 7))
print("")

print (array * 2)

[[0 1]
 [2 3]]

[[ 0  1]
 [ 8 27]]

[[ 7  8]
 [ 9 10]]

[[0 2]
 [4 6]]


### Problem 4
In the code cell below, write a Python script that uses NumPy to create two arrays: one called `students` with `'Janet'`, `'Adriana'`, `'Manual'`, `'Mohamed'`, `'Leann'` as values and another called `grades` with `[93, 85]`, `[78, 80]`, `[94, 93]`, `[75, 90]`, `[92, 87]` as values. Using Boolean indexing (as shown in [Section 4.1](https://wesmckinney.com/book/numpy-basics#ndarray_boolean)), select all rows from `grades` where `students` is either `'Janet'` or `'Leann'`. Remember, to combine multiple Boolean conditions, use Boolean arithmetic operators like `&` (and) and `|` (or). Print both arrays and the result from `grades` after indexing. (5 pts.)

In [230]:
import numpy as np

names = np.array(["Janet", "Adriana", "Manual", "Mohamed", "Leann"])

grades = np.array ([[93, 85], [78, 80], [94, 93], [75, 90], [92, 87]])


cond = (names == 'Janet') | (names == 'Leann')
selected_grades = grades[cond]

print ("Students names:")
print (names)

print ("\nGrades:")
print (grades)

 

print("\nSelected Grades for 'Janet' and 'Leann':")
print(selected_grades)

Students names:
['Janet' 'Adriana' 'Manual' 'Mohamed' 'Leann']

Grades:
[[93 85]
 [78 80]
 [94 93]
 [75 90]
 [92 87]]

Selected Grades for 'Janet' and 'Leann':
[[93 85]
 [92 87]]


### Problem 5
In the code cell below, write a Python script that uses NumPy to calculate the mean of all the grades stored in the `grades` array you created in the previous problem. Use NumPy method `mean` to calculate this (as shown in [Section 4.4](https://wesmckinney.com/book/numpy-basics#ndarray_statistics)). Next, use `np.where()` (also from [Section 4.4](https://wesmckinney.com/book/numpy-basics#numpy_where)) to create a Boolean array that will print `True` when the student's grade is greater than the overall class mean you just calculated and `False` when it is not. Print the mean and the resulting Boolean array. (5 pts.)

In [233]:
import numpy as np

students=np.array(['Janet', 'Adriana', 'Manual', 'Mohamed', 'Leann'])

print ("grades:")
print (grades)
grades=np.array([[93, 85], [78, 80], [94, 93], [75, 90], [92, 87]])

print("")
print(f'grades.mean() == {grades.mean()}')
result= np.where(86.7)
result

print("")
grades > 86.7


grades:
[[93 85]
 [78 80]
 [94 93]
 [75 90]
 [92 87]]

grades.mean() == 86.7



array([[ True, False],
       [False, False],
       [ True,  True],
       [False,  True],
       [ True,  True]])

### Problem 6
The following students signed up for another class, `['Frank', 'Fernando', 'Manual', 'Shannon', 'Leann', 'Deborah']`. How many of these students are also students included in the array you created in Problem 4 above. __Hint__: This can be accomplished using the NumPy `in1d` function. (3 pts.)

In [3]:
import numpy as np

students1=np.array(['Janet', 'Adriana', 'Manual', 'Mohamed', 'Leann'])
students2=np.array(['Frank', 'Fernando', 'Manual', 'Shannon', 'Leann', 'Deborah'])

result = np.in1d(students1, students2, ['Frank', 'Fernando', 'Manual', 'Shannon', 'Leann', 'Deborah'])
print (result)
print(f'Students in both classes: {sum(np.in1d(students1, students2))}')



[False False  True False  True]
Students in both classes: 2


### Problem 7
The students from Problem 6 need to split up to form 3 groups of 2. Use a single line of code to convert the array to a matrix with 3 rows and 2 columns. (2 pts.)

In [7]:
print(students2.reshape(3,2))

[['Frank' 'Fernando']
 ['Manual' 'Shannon']
 ['Leann' 'Deborah']]


## Part 2

### Problem 1
In the code cell below, write a Python script that uses NumPy to simulate rolling a standard 6-sided die 10 times using an approach similar to that shown in [Section 4.7 Example: Random Walks](https://wesmckinney.com/book/numpy-basics#example_random_walks). First, create a fresh random number generator using `seed=54321`. Next, use the `integers` method as shown in [Section 4.7](https://wesmckinney.com/book/numpy-basics#example_random_walks) and detailed in the [NumPy documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html) to generate the 10 random rolls of the die. Use the NumPy `unique` method (described in [Section 4.4](https://wesmckinney.com/book/numpy-basics#numpy_algos_sets)) to find the unique values rolled in your array of random rolls. It's entirely possible that not all values from 1-6 came up in only 10 random rolls. If you used the specified random seed correctly, no 2 should have come up in the first 10 rolls. Print the resulting array of random rolls and the unique values from it. (5 pts.)

In [9]:
import numpy as np

rng= np.random.default_rng(seed=54321) 
random_rolls = rng.integers(1, 7, size=10)
print(random_rolls)

unique_rolls=np.unique(random_rolls)
print (unique_rolls)

[1 5 6 6 4 3 5 1 3 3]
[1 3 4 5 6]


### Problem 2
Create a fresh random number generator using `seed=123123`. Next, define a new variable called `rarray` as a 2 by 3 array filled with random integers from 0 to 100 (inclusive). Print your array. (3 pts.)

In [48]:
rng=np.random.default_rng(seed=123123)
rarray=rng.integers(0, 101, size= (2, 3))
print(rarray)

[[ 9 62 33]
 [28 91 82]]


### Problem 3
Sort `rarray` so that each row is in ascending order. Print your array to confirm your result. (2 pts.)

In [49]:
import numpy as np

print("Sorted Array:")
sorting = np.sort(rarray)
print (sorting)

Sorted Array:
[[ 9 33 62]
 [28 82 91]]


### Problem 4
Create a fresh random number generator using `seed=321321`. Next, define a new variable called `rarray2` as a 1 by 3 array filled with random integers from 0 to 100 (inclusive). Print this array. (3 pts.)

In [57]:

rng2=np.random.default_rng(seed=321321)
rarray2=rng.integers(0, 101, size= (1,3))
print(rarray2)

[[28 43 51]]


### Problem 5
Use broadcasting to divide `rarray` by `rarray2` and save the result as a variable called `resarray`. Print this array. (2 pts.)

In [58]:
print ("resarray:")
resarray= rarray/rarray2
print (resarray)


resarray:
[[0.32142857 1.44186047 0.64705882]
 [1.         2.11627907 1.60784314]]


### Problem 6
Even though both arrays contain integers, what do you notice about the resulting array that supports NumPy's ability to convert between numeric types? Print the data type of `resarray` to support your conclusion. (2 pts.)

In [60]:
#NumPy has the ability to perform operations that involve arrays with different numeric types. In the case of division operation, even though both rarray and rarray2 contain integers, the result might be represented as floating-point numbers if the division doesn't yield an integer.
#To support this, we printed the data type of resarray using the dtype function:
print('Array:', resarray)
 
print('Datatype:', resarray.dtype)

Array: [[0.32142857 1.44186047 0.64705882]
 [1.         2.11627907 1.60784314]]
Datatype: float64


### Problem 7
Calculate the sum of the rows of `resarray` and save it in a variable called `sumarray`. Print this array. (3 pts.)

In [64]:

sumarray = resarray.sum(axis = 1)
print(f'sumarray:{sumarray}')

sumarray:[2.41034786 4.72412221]


### Problem 8
Create a fresh random number generator using `seed=121212`. Next, _flatten_ the contents of `rarray` as shown in [Appendix A section Reshaping Arrays](https://wesmckinney.com/book/advanced-numpy#numpy_reshaping) and then use your random number generator to shuffle the contents of `rarray` using method `shuffle` as shown in the [NumPy documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html). Finally, reshape your shuffled data back into a 2 by 3 array and print this array. (5 pts.)

In [76]:
rng2 = np.random.default_rng(seed = 121212)
rarray = rarray.flatten()
rng2.shuffle(rarray)

print(f'rarray:\n{rarray.reshape(2,3)}')

rarray:
[[ 9 62 33]
 [28 91 82]]
